# Generated by Django 4.2.9 on 2024-01-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_teacher_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
    ]
