# Generated by Django 5.0.1 on 2024-01-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_student',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
