# Generated by Django 4.2.9 on 2024-01-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_is_student_profile_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.TextField(default='Engineering'),
        ),
    ]
