# Generated by Django 4.2.9 on 2024-03-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_attemptquiz_right_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.quiz'),
        ),
    ]
